spring:
  datasource:
    url: jdbc:mysql://120.26.127.190:3306/art_zhejiangart_
    username: art_zhejiangart_

    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: 120.26.127.190
      port: 6379
      # 如果Redis设置了密码，需要添加password配置
      # password: ${REDIS_PASSWORD}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 20
          max-wait: 1000ms
          max-idle: 10
          min-idle: 2
        shutdown-timeout: 100ms

# MyBatis配置
mybatis-plus:
  type-aliases-package: cn.com.zhejiangart.model.vo
  mapper-locations: classpath:mapper/*.xml

# SpringDoc OpenAPI 配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    deep-linking: true
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.com.zhejiangart.controller
  show-actuator: true
  paths-to-exclude: /error
  packages-to-scan: cn.com.zhejiangart.controller, cn.com.zhejiangart.model
  # 启用对Swagger注解的完全支持
  cache.disabled: true

# 上传配置
upload:
  # 当前上传方式 （local,oss,cos）
  type: oss
  # 允许上传的文件类型
  allow-ext: doc,gif,ico,icon,jpg,mp3,mp4,p12,pem,png,rar,jpeg
  # 允许上传的大小
  allow-size: 10240000
  # 允许上传的文件mime
  allow-mime: image/gif,image/jpeg,video/x-msvideo,text/plain,image/png
  # 可用的上传文件方式
  allow-type: local,oss,cos,qnoss
  # 本地上传路径
  local-path: ./uploads/
  # 阿里云oss配置
  oss:
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucket: zjmsw
    domain: zjmsw.oss-cn-hangzhou.aliyuncs.com

# 微信配置
wechat:
  # 微信公众平台配置
  mp:
    app-id: ${WECHAT_MP_APP_ID}
    secret: ${WECHAT_MP_SECRET}
  # 微信支付配置
  pay:
    # 应用ID
    app-id: ${WECHAT_PAY_APP_ID}
    # 商户号
    mch-id: ${WECHAT_PAY_MCH_ID}
    # 商户APIv3密钥
    api-v3-key: ${WECHAT_PAY_API_V3_KEY:}
    # 商户API私钥路径
    private-key-path: classpath:apiclient_key.pem
    # 商户证书序列号
    serial-no: ${WECHAT_PAY_SERIAL_NO}